language: python

python:
- '2.7'

sudo: required

services:
- docker

notifications:
  email:
    recipients:
    - tgu@anl.gov
    on_success: never
    on_failure: always

env:
  global:
    secure: vaUXBwg0sJwKduIqiTDsABSQFu06E+UvNFWeUbnuyfvBnAjz7p5DsaG6Rx/B7tcn4hpZUj91VoimKtbtKRhiXxROGWSHmwT3eiaHlYsJuoRyrQv+5kF0aa2tnpF/+t4b+a7uV1T1mwDDqS6+aDq3PUAr89sEFaYzT7Rir8hbJeiXeUCHilAR65AbtvO1K027fZpc4K4MLTadfjfAoeP9RrhjmreWwRwh4rq3XenU8fJBs1y6vLcrOvs/F3VcNriNWSP8XIe1D58We3AD7PPNgucwVEdOeAYj7O/Btnpe6MzJBB/wyuoJ0sMlGk81LKhZUtB35QKMN+uvZirQtE3JipVjbZIE0RGTrfhtdmE96iAlfFpPPr9jRM9a1KyK7SChwKZ27x3I6l2+lZRO1hRsechj/YsKHsXYqErALE2x2sMA+10gFHLFZVX54PCofLgQFi+it1VOr/gJu+y63srYoO2OrnPlzHmNYxMx76/t1c+9QZLVsoulxRRp3tldYdx8IkFSb0Tfh/hE0pBqujw3q1kCm8IB9pW+/pdDJ9Hlk1B/RFi2aoDa8MvuxGx5ij5WWGiLOzg9KjRG7fliNEPYocaV4l+Fi4AqjEoFdUgoGAtBx14p3JnB4of/IU2YEopD2GWC7Z20FnRhgRgAXOCbiH4J26rBoe0hA4BDyfn9AZ4=

branches:
  only:
  - master

before_install:
- docker version
- python --version
- javac -version
- java -version

install:
- pip install coveralls
- git clone https://github.com/kbase/jars
- git clone https://github.com/kbase/kb_sdk
- cd kb_sdk
- make
- make sdkbase
- docker images
- export PATH=$(pwd)/bin:$PATH
- cd ../
- git clone https://github.com/Tianhao-Gu/kb_deseq.git
- cd kb_deseq
- kb-sdk test || true
- sed -i "s/test_token=/test_token=$TEST_TOKEN/" test_local/test.cfg
# - sed -i 's\https://appdev.kbase.us/services\https://ci.kbase.us/services\' test_local/test.cfg
# - sed -i 's\https://appdev.kbase.us/services/auth/api/legacy/KBase/Sessions/Login\https://ci.kbase.us/services/auth/api/legacy/KBase/Sessions/Login\'
#   test_local/test.cfg
- sed -i 's/$(id -u)/0:0/' test_local/run_tests.sh
- pwd=$(pwd)
- echo "#!/bin/bash" >> test_local/run_subjob.sh
- echo -e "$pwd/test_local/run_docker.sh run --rm --user 0:0 -v $pwd/test_local/subjobs/\$1/workdir:/kb/module/work
  -v $pwd/test_local/workdir/tmp:/kb/module/work/tmp \$4 -e \"SDK_CALLBACK_URL=\$3\"
  \$2 async" >> test_local/run_subjob.sh
- cat test_local/run_subjob.sh

script:
- kb-sdk test

after_success:
- cp test_local/workdir/.coverage .
- sudo mkdir -p /kb/module/lib/
- sudo cp -R test_local/workdir/kb/module/lib/kb_deseq /kb/module/lib/
- pwd
- ls -l /kb/module/lib/kb_deseq
- cat .coverage
- coverage report -m
- coveralls